version: '3.3'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - mynetwork
  nginx:
    container_name: nginx-php
    image: nginx 
    ports:
            - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - mynetwork

networks:
  mynetwork:
