# Generated by Django 3.0.7 on 2022-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sets', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('sheeturl', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=5)),
                ('set', models.CharField(max_length=2)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='max_rank_buckets',
            fields=[
                ('branch', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bucket95_max_rank', models.IntegerField(default=0)),
                ('bucket90_max_rank', models.IntegerField(default=0)),
                ('bucket85_max_rank', models.IntegerField(default=0)),
                ('bucket80_max_rank', models.IntegerField(default=0)),
                ('bucket75_max_rank', models.IntegerField(default=0)),
                ('bucket70_max_rank', models.IntegerField(default=0)),
                ('bucket65_max_rank', models.IntegerField(default=0)),
                ('bucket60_max_rank', models.IntegerField(default=0)),
                ('bucket55_max_rank', models.IntegerField(default=0)),
                ('bucket50_max_rank', models.IntegerField(default=0)),
                ('bucket45_max_rank', models.IntegerField(default=0)),
                ('bucket40_max_rank', models.IntegerField(default=0)),
                ('bucket35_max_rank', models.IntegerField(default=0)),
                ('bucket30_max_rank', models.IntegerField(default=0)),
                ('bucket25_max_rank', models.IntegerField(default=0)),
                ('bucket20_max_rank', models.IntegerField(default=0)),
                ('bucket15_max_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set', models.CharField(default='', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
