# Generated by Django 3.0.7 on 2022-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankestimate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
