# Generated by Django 3.0.7 on 2022-01-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankestimate', '0002_auto_20220122_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='max_rank_buckets',
            new_name='MaxRankBuckets',
        ),
    ]
