# Generated by Django 3.0.7 on 2022-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankestimate', '0003_auto_20220122_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('validdomain', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
