# Generated by Django 3.0.7 on 2022-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankestimate', '0005_domains_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='year',
            field=models.CharField(default='2021', max_length=10),
        ),
    ]
