# Generated by Django 3.0.7 on 2022-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankestimate', '0006_marks_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.FloatField(),
        ),
    ]
